name: Download and create repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "guinnessgshep@gmail.com"
          git config --global user.name "Guinness Shepherd"

      - name: Download files from specific branch
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git clone --branch development --single-branch https://guinnessshep:${PERSONAL_TOKEN}@github.com/emkey1/ish-AOK.git

      - name: Create new repository and push
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          cd ish-AOK
          curl -u "guinnessshep:${PERSONAL_TOKEN}" https://api.github.com/user/repos -d '{"name":"ishdev"}'
          git remote set-url origin https://github.com/guinnessshep/ishdev.git
          git push -u origin development
